version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=dweapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  weclapp-manager:
    image: ghcr.io/dweberatunggmbh/dweapp:latest
    ports:
      - "3000:3000"
    volumes:
      - ./prisma:/app/prisma:ro
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/dweapp
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - NEXT_PUBLIC_WECLAPP_API_URL=https://dwe.weclapp.com/webapp/api/v2
      - NEXT_PUBLIC_WECLAPP_API_KEY=56eb9c41-5f17-42d3-a96b-b2b561254bfc
      - NEXT_PUBLIC_AZURE_AD_CLIENT_ID=25e2203c-f668-482f-acdb-e758de9aef23
      - NEXT_PUBLIC_AZURE_AD_TENANT_ID=16fb7d46-199f-417d-9460-ebb505438d0c
      - NEXT_PUBLIC_REDIRECT_URI=https://91.98.135.191/api/auth/callback/azure-ad
      - NEXT_PUBLIC_CLOCKIN_API_URL=https://customerapi.clockin.de/v3
      - NEXT_PUBLIC_CLOCKIN_API_KEY=781158|PwbBiOEkaL8zNMzlRlNvYAIQZyDs3TaMJpAhzx6o49312f6d
      - NEXTAUTH_URL=https://91.98.135.191
      - NEXTAUTH_SECRET=XRHONL5pphqWZ0wEVp56nefJiSi9t444I7fmdbIgdes=
      - AZURE_AD_CLIENT_SECRET=dein-secret
      - AZURE_AD_CLIENT_SECRET_ID=dein-id
      - WECLAPP_WEBHOOK_SECRET=dein-geheimes-webhook-secret-12345
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/weclapp-manager/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs/weclapp-manager.crt:/etc/ssl/certs/weclapp-manager.crt:ro
      - /etc/ssl/private/weclapp-manager.key:/etc/ssl/private/weclapp-manager.key:ro
    depends_on:
      - weclapp-manager
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
